name: QE
run-name: ${{ github.actor }} is testing QE 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: espressofoundation/ubuntu:latest
    steps:
      - run: |
            apt-get install -y libfftw3-3 libfftw3-dev libfftw3-doc
            DFLAGS='-D__OPENMP -D__FFTW3 -D__MPI -D__SCALAPACK' FFT_LIBS='-lfftw3'  ./configure --enable-openmp
            make pw
